# Generated by Django 5.1.7 on 2025-03-25 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Client', '0001_initial'),
        ('Service', '0001_initial'),
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.customer')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.addproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Service_Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.customer')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service.service')),
            ],
        ),
    ]
