# Generated by Django 5.1.7 on 2025-03-25 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=100)),
                ('Catagory', models.CharField(max_length=200)),
                ('cost', models.FloatField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/images/')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, max_length=20, null=True)),
                ('payment', models.CharField(choices=[('Bkash', 'Bkash'), ('Rocket', 'Rocket'), ('Cash On Delivery', 'Cash On Delivery')], default='Cash On Delivery', max_length=30)),
                ('transaction_id', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.addproduct')),
            ],
        ),
    ]
